# ______ _                       ___________ _   __ #
# | ___ \ |                     /  __ \  _  \ | / / #
# | |_/ / | __ _ _   _  ___ _ __| /  \/ | | | |/ /  #
# |  __/| |/ _` | | | |/ _ \ '__| |   | | | |    \  #
# | |   | | (_| | |_| |  __/ |  | \__/\ |/ /| |\  \ #
# \_|   |_|\__,_|\__, |\___|_|   \____/___/ \_| \_/ #
#                 __/ |                             #
#                |___/                              #

# 全局设置
options:
  # 插件更新提醒
  update: true
  # bStats数据统计
  metrics: true
  # 数据库相关配置
  database:
    # 数据储存类型
    # 可用: LOCAL, SQL
    use: LOCAL
    # 数据储存配置
    source:
      SQL:
        host: localhost
        port: 3306
        user: root
        password: root
        database: test
        table: playercdk
# 模块设置
module:
  # 兑换码模块
  CDK:
    # 兑换码模块
    enable: true